spring:
    datasource:
      url: jdbc:h2:mem:alert
      username: sa
      password: password
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
        path: /h2-console
logging:
  level:
    root: WARN
    org.springframework.web: INFO
    github.pedrozaz.pricealert: INFO