pring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:alert
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ## INSERT YOUR EMAIL HERE ##
    password: ## INSERT YOUR APP PASSWORD HERE ##
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
cors:
  origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:4200}

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    github.pedrozaz.pricealert: DEBUG